# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/
# relative_permalinks: true

# Setup
title:            JW's Blog
tagline:          'none'
description:      '포스팅으로 생각을 정리하자'
url:              https://woin2ee.github.io/
baseurl:          /

author:
  name:           'Jaewon Yun'
  url:            https://github.com/woin2ee

paginate:         5

timezone: Asia/Seoul

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/woin2ee/woin2ee.github.io

plugins: [jekyll-paginate, jekyll-gist]

categories: [ Posts ]


